### ISSUE TITLE
引用的时候，出现这个问题，怎么处理？

### ISSUE THREAD

**Issue by GameDT** [canyinghao/CanDialog#1]
![123](https://cloud.githubusercontent.com/assets/19942990/16477392/c23d807c-3ec3-11e6-9f9f-e5eac092aa9a.png)
![456](https://cloud.githubusercontent.com/assets/19942990/16477395/c9065302-3ec3-11e6-9f9b-bf1aa8273623.png)
出现这个问题，这怎么处理

**Comment by canyinghao** [comment]
这个是vector-compat这个依赖库出问题了，好像Androidstudio升级2.0以后就会出现这问题。ic_stop_vector.xml文件里有一句 android:pathData="@string/path_stop"，解析时遇到string/里面的g/就解析报错了。解决办法就是将vector-compat的代码全部考入自己的工程，修改xml里面android:pathData="@string/path_stop"这样的语句，直接将string里面的考过来，不使用@string/path_stop样式。

**Comment by GameDT** [comment]
谢谢你，问题解决了，电脑配置不行，弄了好久，这是我用的vector-compat依赖库的地址https://github.com/wnafee/vector-compat
希望能帮助后续遇到这个问题的程序猿，不过有点缺陷，vector-compat依赖库好像好久没更新了，compileSdkVersion 22
buildToolsVersion "22.0.1"，高了会报错。
![789](https://cloud.githubusercontent.com/assets/19942990/16479649/5af89f62-3ed4-11e6-82a2-5fa5f55fafaa.jpg)
我删除了vector-compat依赖库中DrawableCompat.class和AnimatedVectorDrawable.class一些重写的方法，下图所示，可以编译通过了，运行Dialog动画都可以实现，不过不知道有没有BUG，哈哈。
![1](https://cloud.githubusercontent.com/assets/19942990/16480908/37c59c46-3edb-11e6-9486-0dc699425518.jpg)
![2](https://cloud.githubusercontent.com/assets/19942990/16480852/feddf612-3eda-11e6-99a3-0d1458bb31f6.jpg)
![3](https://cloud.githubusercontent.com/assets/19942990/16480866/102c15ca-3edb-11e6-9182-32e5e62cbc8d.jpg)
