### ISSUE TITLE
Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout

### ISSUE THREAD

**Issue by GameDT** [canyinghao/CanDialog#2]
测试的Module可以运行，在自己的Module里不知道是什么原因，一直报这个错误，怎么解决？
![4](https://cloud.githubusercontent.com/assets/19942990/16510200/8fba92a8-3f76-11e6-857b-b18b2da67931.jpg)

**Comment by canyinghao** [comment]
你需要延迟弹出dialog，或者响应事件弹出dialog才行，直接放在setContentView后面，因view还未实例化完成，会出现问题。
